setup: &setup
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 5
  password:

production:
  <<: *setup
  database: blog_rails_production
  username: blog_rails_production

staging:
  <<: *setup
  database: blog_rails
  username: blog_rails_staging
  password: blog_rails_staging_password

development:
  <<: *setup
  database: blog_rails_development

test:
  <<: *setup
  database: blog_rails_test
